### ISSUE TITLE
Vehicle Physics Pro Community Edition Integration

### ISSUE THREAD

**Issue by mozhoku** [autowarefoundation/AWSIM-Labs#108]
Default tools in Unity is simple and can't simulate vehicle behaviour properly. Using VPP for more detailed vehicle simulation would be better for the AWSIM Labs users. It also can handle different types of [vehicle configurations](https://vehiclephysics.com/about/features/#feature-examples).

For further information about the package:
Asset Store: https://assetstore.unity.com/packages/tools/physics/vehicle-physics-pro-community-edition-153556
Website: https://vehiclephysics.com/

**Comment by sasa42** [comment]
+1

fyi,  fantastic project done with VPP...

https://github.com/PERRINN/project-424-unity

I did an HDRP test on an older version.

https://github.com/sasa42/project-424-unity.git
branch HDRP_Drive_Test
https://youtu.be/EyVYKxtS6uE?feature=shared

- Q key for FastestLap SelfDrive
- key 1 to 4 for cams
- wasd keys for drive

The integration would be easy to do.
Even a live toogle from actual unity script to vpp script.

**Comment by sasa42** [comment]
I think Edy Garcia would provide an integration script so that VPP switch works in one click. I will give him a message and link to this issue.

**Comment by roboserg** [comment]
Any updates on this?

**Comment by xmfcx** [comment]
VPP has been integrated and being used within AWSIM Labs ✅
