### ISSUE TITLE
Implement traffic control features through UI

### ISSUE THREAD

**Issue by mozhoku** [autowarefoundation/AWSIM-Labs#11]
Hi!
I'm planning to give users control over traffic via GUI.

### Proposed Features
- **Traffic Control in GUI**: Enable resetting, stopping, and restarting of traffic directly from the ESC menu.
- **Parameter Adjustment**: Allow users to modify the seed for traffic generation.
- **Shortcut Key**: Implement a key binding for enable/disable traffic flow for convenience.

 With this, users will have more control over traffic in the runtime. 

Please share your thoughts and any suggestions you have. 🤗

**Comment by doganulus** [comment]
Is such traffic control available programmatically? Via ROS topics or using some other way?

**Comment by mozhoku** [comment]
> Is such traffic control available programmatically? Via ROS topics or using some other way?

Not that I'm aware of. But it should be possible.

**Comment by xmfcx** [comment]
Let's skip "Shortcut Key" option for this issue, we can consider hotkeys in an issue dedicated to hotkey management in general.

**Comment by mozhoku** [comment]
- https://github.com/autowarefoundation/AWSIM/pull/17

Changes are merged. Closing this issue.
