### ISSUE TITLE
Make sure all scenes work with URP

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/AWSIM-Labs#12]
## Description

We have recently finished:
- https://github.com/autowarefoundation/AWSIM/issues/10

But only the main AutowareSimulation scene was tested.

## Definition of done

- [ ] List all scenes in the project
- [ ] Make sure all work with URP

**Comment by mozhoku** [comment]
Changes are merged to main branch @xmfcx. 
- https://github.com/autowarefoundation/AWSIM/pull/19

Thank you for your contribution @Aysenayilmaz
