### ISSUE TITLE
Create a new map: Parking Lot

### ISSUE THREAD

**Issue by armaganarsln** [autowarefoundation/AWSIM-Labs#121]
In order to test of new parking planner in this https://github.com/orgs/autowarefoundation/discussions/4936

We need a simulation testing environment. The environment should consist of different types of parking areas such as regular, angled, and parallel parking. Here is an example image of how it could be.

The parking areas for parallel parking will be 2.5m wide and the length will be 1.5 x the car length. The length will depend on the selected vehicle.

The road in the area should be two-way in all the parking areas and have a 7m width.

![image](https://github.com/user-attachments/assets/dc730948-d421-466a-abed-49d4027f1fd5)

For checking a similar test here is a video done by a Tesla driver: https://www.youtube.com/watch?v=2dbPrltSTp0

In the simulation environment, the parking areas should be busy and vehicles should be trying to park between cars in most test cases.

**Comment by xmfcx** [comment]
We can start this once:
- https://github.com/autowarefoundation/AWSIM-Labs/pull/96
is merged.

**Comment by sasa42** [comment]
I like to put this map into the loop...

![maxresdefault](https://github.com/user-attachments/assets/58914766-c7c4-461d-a776-9b09f1f7b0b8)
![zzalazonepalyaalazonepalya](https://github.com/user-attachments/assets/ac4875ac-efd0-4b06-8330-1badfd075619)


Zala Zone Smart City

I did a quick review because i searched a test ground with complete city (focused on an  adas feature set)

I downloaded the Unity Road and Env mesh. Also the point clouds and found a LanLet2 set for smart city on github.

So there would me a full set of scenarios and even a big parking place. ( right on sscreenshot)

I will add some shots from the data later.

**Comment by sasa42** [comment]
Mesh....
1+2+3 could be extended parking spaces

![zz_parking](https://github.com/user-attachments/assets/f9e22e31-6018-4c02-940b-2423d24a8012)

OSM Lanes
![osm_lanes](https://github.com/user-attachments/assets/4cbf786b-19df-4121-98f0-0b694a872742)

LaneLet2
https://github.com/jkk-research/lanelet2_maps

**Comment by armaganarsln** [comment]
@sasa42 after preparing the required map we will try to import this one as well and test. Our aim is to create a very simple one so that the developers in planning could test with their laptop. Currently they are using 2D simulator and we are trying to move them to AWSIM. This area might be too big and might result in performance decrease therefore I can't promise but we will definitely test and give you feedback. Thank you for your suggestion.

**Comment by Aysenayilmaz** [comment]
**_Update on the current status of the environment:_**

Three different parking area were created: parallel parking, L parking, and angled parking. Adjustments and improvements will be made to the environment. It will also be tested and reported using the current parking planner.


![Screenshot from 2024-07-24 18-39-57](https://github.com/user-attachments/assets/0dc20062-649d-4e9e-bc7d-502e9feaf8c9)
![Screenshot from 2024-07-24 18-40-12](https://github.com/user-attachments/assets/189bc0b8-612c-4df4-b5a8-2239f0af33d1)
![Screenshot from 2024-07-24 18-40-40](https://github.com/user-attachments/assets/17533672-e1e6-4358-913a-8b96565e5263)
![Screenshot from 2024-07-24 18-41-11](https://github.com/user-attachments/assets/b51bcb9a-52ea-4dbe-b81a-34043e980b45)

### **Dimensions of the Parking Spaces**
_(The unit of measurement is in metres.)_

- Parallel Parking: 3 x 7.275 (The dimensions were set to 1.5 times the size of the Lexus vehicle.)
![Screenshot from 2024-07-25 10-29-29](https://github.com/user-attachments/assets/efc08019-d0c9-47f2-9465-21f013297ebc)

- L Parking: 2.5 x 6
![Screenshot from 2024-07-25 10-30-11](https://github.com/user-attachments/assets/58d6d752-3812-4cb4-ae99-2e3c14a84bc7)


- Angled parking : 7 x 3 & 60-degree
![Screenshot from 2024-07-25 10-31-37](https://github.com/user-attachments/assets/da344c9d-ba9f-4366-9eb0-fd7c3d863008)

**Comment by Aysenayilmaz** [comment]
**_Update on the current status of the environment:_** 
- The pointcloud map and HD-map of the environment have been created.
- L parking has been tested.
https://youtu.be/7PW41OYb4b8

- Parallel parking has been tested.
https://youtu.be/A4k5VDHK4eg

- Angled parking has been tested.
https://youtu.be/RS-P24wmZxE

**Comment by Aysenayilmaz** [comment]
The binary file, pcd, and hd-map have been added to the new release. https://github.com/autowarefoundation/AWSIM-Labs/releases/tag/v1.2.0 

- The binary file :  [awsim_labs_parking_v1.2.0.zip](https://github.com/autowarefoundation/AWSIM-Labs/releases/download/v1.2.0/awsim_labs_parking_v1.2.0.zip)  
- pcd and hd-map :  [awsim_labs_ParkinArea.zip](https://github.com/autowarefoundation/AWSIM-Labs/releases/download/v1.2.0/awsim_labs_ParkinArea.zip)

**Comment by armaganarsln** [comment]
Thanks @Aysenayilmaz , since the binaries are released, we can close this issue.

**Comment by Aysenayilmaz** [comment]
The dimensions of the parking spaces were made based on this reference: 

- https://cdn-wordpress.webspec.cloud/intrans.iastate.edu/uploads/sites/15/2018/12/Chapter_08-2018.pdf
- https://www.dimensions.com/element/30-degree-parking-spaces-layouts
