### ISSUE TITLE
Null references and no ROS topics when running simulation from Unity Editor

### ISSUE THREAD

**Issue by WilliamFlinchbaugh** [autowarefoundation/AWSIM-Labs#125]
I'm getting tons of null references and no topics when running either the AutowareSimulation or AutowareSimulationScenario scenes. The regular demo and ss2 demo work fine.

What I've tried:
* I setup my DDS configuration correctly (However I don't have ROS_LOCALHOST_ONLY=1 as per the docs instructions)
* I don't have ROS2 sourced in .bashrc or .profile, so the editor should not have ROS2 sourced
* Tried cloning the repository again
* Tried with both Nishishinjuku_URP_v0.1.0 and v0.2

After running the simulation from the editor, calling `ros2 topic list` only returns `/parameter_events` and `/rosout`.

Note: I downgraded my nvidia drivers to 535 because the editor would crash on startup with 555 and 550.

![image](https://github.com/user-attachments/assets/af8499f9-8ead-4573-b6fc-726b897d0738)

**Comment by Aysenayilmaz** [comment]
@WilliamFlinchbaugh Are you running UnityHub from the terminal? You can get the same error if you open the editor and start the scene without running UnityHub from the terminal. 
![Screenshot from 2024-07-26 10-44-16](https://github.com/user-attachments/assets/92390d56-6a02-4036-b000-91a77ba0f47a)

**Comment by WilliamFlinchbaugh** [comment]
@Aysenayilmaz Yep, that was it. I missed the little warning in the docs. This might be worth putting in the troubleshooting section as well, but maybe I'm just stupid. Thank you!
