### ISSUE TITLE
R hotkey is used by multiple functions

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/AWSIM-Labs#13]
## Description

- https://github.com/autowarefoundation/AWSIM/issues/7

was recently merged. But the R hotkey is also used to switch to reverse gear.

## Definiton of done

- [ ] Use CTRL+R instead for resetting position

**Comment by mozhoku** [comment]
I'm fixing this issue in my PR here: 
- https://github.com/autowarefoundation/AWSIM/pull/36
