### ISSUE TITLE
add parking environment for multi-scene setup

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/AWSIM-Labs#133]
We have AWSIM with parking lot environment available as a separate binary as mentioned in [this comment](https://github.com/autowarefoundation/AWSIM-Labs/issues/121#issuecomment-2263517324), but we could have this environment available for the user through pull-down menu in multi-scene setup.

![image](https://github.com/user-attachments/assets/5162db4a-5afc-42cf-9dde-4629ea4f2154)

**Comment by Aysenayilmaz** [comment]
In the new release, 'awsim_labs_v1.3.1,' environments can be selected. Shinjuku and Parking Area have been added. 

- https://github.com/autowarefoundation/AWSIM-Labs/releases
- https://github.com/autowarefoundation/AWSIM-Labs/releases/download/v1.3.1/awsim_labs_v1.3.1.zip

**Comment by maxime-clem** [comment]
@Aysenayilmaz I downloaded the latest binary `v1.4.0` but the parking area does not appear in the drop down menu. Was it removed ?

**Comment by Aysenayilmaz** [comment]
@maxime-clem The Parking Area was missing in the loader scene, but it has now been updated. 
- https://github.com/autowarefoundation/AWSIM-Labs/releases/tag/v1.4.1
