### ISSUE TITLE
AWSIM keyboard input not working

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/AWSIM-Labs#138]
I have noticed that there is a guide about VehicleKeyboardInput.cs shown in the Hotkeys panel, but vehicle does not respond to the keyboard input.

We should either remove the guide if the function is not on, or we should enable the function by default.

![image](https://github.com/user-attachments/assets/11a96137-f965-4106-bb04-29848c863205)

**Comment by Aysenayilmaz** [comment]
@mitsudome-r  Before driving with the keyboard, you need to click on the keyboard icon under the Ego Vehicle section. Did you do this? 

![Screenshot from 2024-09-03 19-07-48](https://github.com/user-attachments/assets/d0c7e08b-2cda-43c4-8db1-c174cdc21480)

**Comment by mitsudome-r** [comment]
Thanks! I wasn't aware that there was a button there.
