### ISSUE TITLE
Improve the documentation for all hotkeys

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/AWSIM-Labs#14]
## Definition of done

- [x] List all the hotkeys used in the project
- [x] Find all the references in the documentation to these hotkeys
- [x] Reorganize the documentation on these hotkeys and unify them in a single place
- [x] Update the hotkey documentation

**Comment by mozhoku** [comment]
Related PR:
- https://github.com/autowarefoundation/AWSIM/pull/38
