### ISSUE TITLE
Button `D` has two different role when manual driving

### ISSUE THREAD

**Issue by StepTurtle** [autowarefoundation/AWSIM-Labs#140]
Since button `D` has a two different role, while manually reversing the vehicle to the right using the keyboard, the vehicle shifts into drive due to pressing the `D` key. (Pressing the `S` and `D` buttons at the same time).

We might consider changing the key configurations.

**Comment by mozhoku** [comment]
Yes, the controls will be changed with this PR soon. You can drive with arrow keys for now.
- https://github.com/autowarefoundation/AWSIM-Labs/pull/116

**Comment by mozhoku** [comment]
I'm closing this issue since the changes are applied to the main branch. :+1:
