### ISSUE TITLE
Automatic assignment of pedal maps to `raw_vehicle_cmd` node

### ISSUE THREAD

**Issue by mozhoku** [autowarefoundation/AWSIM-Labs#144]
People forget to copy pedal maps to `raw_vehicle_converter` node. Should be updated in the `awsim_labs_vehicle_launch` to include these maps.

**Comment by xmfcx** [comment]
@Aysenayilmaz could you remove the step 8 from https://autowarefoundation.github.io/AWSIM-Labs/main/GettingStarted/QuickStartDemo/ as well?

**Comment by xmfcx** [comment]
Closing since the task is completed.
