### ISSUE TITLE
Vehicle Accelerates Slowly at Start

### ISSUE THREAD

**Issue by Aysenayilmaz** [autowarefoundation/AWSIM-Labs#154]
The vehicle accelerates very slowly when it starts moving. 
https://youtu.be/7PSN_-AC1bQ

**Comment by mozhoku** [comment]
Pedal map needs to be re-calibrated for this.

**Comment by mozhoku** [comment]
I'm on it.

**Comment by xmfcx** [comment]
- Fixed by: https://github.com/autowarefoundation/awsim_labs_vehicle_launch/pull/6
