### ISSUE TITLE
Fix documentation references to the upstream repository

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/AWSIM-Labs#16]
## Description

Recently this repository was forked. We are also hosting documentation generated from this forked repository.

But some links are absolute and they point to the parent repository. We should update those links.

## Definition of done

- [x] Search for all instances of `tier4.github.io` in the docs folder
- [x] Make sure they all point to this repository
- [x] Make them some of them relative links if possible

**Comment by mozhoku** [comment]
PR link: 
- https://github.com/autowarefoundation/AWSIM/pull/37
