### ISSUE TITLE
The pointcloud layout is not compatible with PointXYZIRCAEDT or PointXYZIRC. Aborting

### ISSUE THREAD

**Issue by HiHeXi** [autowarefoundation/AWSIM-Labs#173]
Errors encountered when using the latest version of AutoTware

The pointcloud layout is not compatible with PointXYZIRCAEDT. Aborting

**Comment by HiHeXi** [comment]
![Uploading 截图 2024-10-25 15-40-11.png…]()

**Comment by HiHeXi** [comment]
![截图 2024-10-25 15-40-11](https://github.com/user-attachments/assets/740325ed-4516-438b-9d91-142f3a270ff7)

**Comment by vividf** [comment]
I think a PR needs to be created to fix the order `PointXYZIRCEADT` to `PointXYZIRCAEDT` in [AWSIM](https://github.com/autowarefoundation/AWSIM-Labs/blob/main/Assets/AWSIM/Scripts/Sensors/LiDAR/PointCloudFormatLibrary.cs#L65C1-L75C20)


@xmfcx  Could someone in awsim lab fix this? Thanks

**Comment by xmfcx** [comment]
@vividf thanks, I've added comments here:
- https://github.com/autowarefoundation/AWSIM-Labs/pull/122#pullrequestreview-2399049161

I will try to fix and release it tomorrow.

**Comment by WilliamFlinchbaugh** [comment]
@xmfcx I tried out implementing those changes (just replacing every instance of PointXYZIRCEADT with PointXYZIRCAEDT), but I'm still getting the same error from autoware. Is there anything else that needs to be changed?

**Comment by xmfcx** [comment]
@vividf @HiHeXi could you try the latest release?

I've fixed it in [v1.5.3](https://github.com/autowarefoundation/AWSIM-Labs/releases/tag/v1.5.3) and tested, it worked for me.

- https://github.com/autowarefoundation/AWSIM-Labs/releases

**Comment by HiHeXi** [comment]
> @vividf @HiHeXi 你能尝试一下最新版本吗？
> 
> 我已经在 [v1.5.3 ](https://github.com/autowarefoundation/AWSIM-Labs/releases/tag/v1.5.3)中修复了它并进行了测试，它对我有用。
> 
>     * [https://github.com/autowarefoundation/AWSIM-Labs/releases ](https://github.com/autowarefoundation/AWSIM-Labs/releases)

Thank you for the update, there are currently new issues. The vehicle is unable to move, detailed logs are as follows

[autoware_ekf_localizer_node-43] [WARN] [1730684733.088041349] [localization.pose_twist_fusion_filter.ekf_localizer]: EKF period may be too slow to finish pose smoothing!! (0.110012 sec) 
[mrm_handler_node-27] [INFO] [1730684733.090250635] [system.mrm_handler]: MRM State changed: MRM_OPERATING -> NORMAL
[mrm_handler_node-27] [WARN] [1730684733.092561258] [system.mrm_handler]: EMERGENCY_STOP is canceled.
[component_container_mt-76] [INFO] [1730684733.092352179] [control.vehicle_cmd_gate]: The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
[autoware_ekf_localizer_node-43] [WARN] [1730684733.192945414] [localization.pose_twist_fusion_filter.ekf_localizer]: EKF period may be too slow to finish pose smoothing!! (0.111061 sec) 
[autoware_ndt_scan_matcher_node-39] [INFO] [1730684733.274911475] [localization.pose_estimator.ndt_scan_matcher]: pose_buffer_.size() < 2
[autoware_ndt_scan_matcher_node-39] [INFO] [1730684733.451575034] [localization.pose_estimator.ndt_scan_matcher]: pose_buffer_.size() < 2
[mrm_handler_node-27] [INFO] [1730684733.463253369] [system.mrm_handler]: MRM State changed: NORMAL -> MRM_OPERATING
[mrm_handler_node-27] [WARN] [1730684733.465992061] [system.mrm_handler]: MRM behavior is None. Do nothing.
[mrm_handler_node-27] [WARN] [1730684733.466432386] [system.mrm_handler]: EMERGENCY_STOP is operated.
[component_container_mt-76] [INFO] [1730684733.548544870] [control.vehicle_cmd_gate]: The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
[mrm_handler_node-27] [INFO] [1730684733.550121389] [system.mrm_handler]: MRM State changed: MRM_OPERATING -> MRM_SUCCEEDED
[component_container_mt-76] [INFO] [1730684733.637345635] [control.vehicle_cmd_gate]: The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
[mrm_handler_node-27] [INFO] [1730684733.639854425] [system.mrm_handler]: MRM State changed: MRM_SUCCEEDED -> NORMAL
[mrm_handler_node-27] [WARN] [1730684733.642659612] [system.mrm_handler]: EMERGENCY_STOP is canceled.
[autoware_ndt_scan_matcher_node-39] [INFO] [1730684733.642663457] [localization.pose_estimator.ndt_scan_matcher]: pose_buffer_.size() < 2
[mrm_handler_node-27] [INFO] [1730684733.773529695] [system.mrm_handler]: MRM State changed: NORMAL -> MRM_OPERATING
[mrm_handler_node-27] [WARN] [1730684733.773618682] [system.mrm_handler]: MRM behavior is None. Do nothing.
[mrm_handler_node-27] [WARN] [1730684733.776007653] [system.mrm_handler]: EMERGENCY_STOP is operated.
[component_container_mt-76] [INFO] [1730684733.810114161] [control.vehicle_cmd_gate]: The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
[mrm_handler_node-27] [INFO] [1730684733.811639112] [system.mrm_handler]: MRM State changed: MRM_OPERATING -> NORMAL
[mrm_handler_node-27] [WARN] [1730684733.812089326] [system.mrm_handler]: EMERGENCY_STOP is canceled.
