### ISSUE TITLE
Errors encountered when using the latest version of Autoware

### ISSUE THREAD

**Issue by HiHeXi** [autowarefoundation/AWSIM-Labs#176]
[autoware_ekf_localizer_node-43] [WARN] [1730684733.088041349] [localization.pose_twist_fusion_filter.ekf_localizer]: EKF period may be too slow to finish pose smoothing!! (0.110012 sec)
[mrm_handler_node-27] [INFO] [1730684733.090250635] [system.mrm_handler]: MRM State changed: MRM_OPERATING -> NORMAL
[mrm_handler_node-27] [WARN] [1730684733.092561258] [system.mrm_handler]: EMERGENCY_STOP is canceled.
[component_container_mt-76] [INFO] [1730684733.092352179] [control.vehicle_cmd_gate]: The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
[autoware_ekf_localizer_node-43] [WARN] [1730684733.192945414] [localization.pose_twist_fusion_filter.ekf_localizer]: EKF period may be too slow to finish pose smoothing!! (0.111061 sec)
[autoware_ndt_scan_matcher_node-39] [INFO] [1730684733.274911475] [localization.pose_estimator.ndt_scan_matcher]: pose_buffer_.size() < 2
[autoware_ndt_scan_matcher_node-39] [INFO] [1730684733.451575034] [localization.pose_estimator.ndt_scan_matcher]: pose_buffer_.size() < 2
[mrm_handler_node-27] [INFO] [1730684733.463253369] [system.mrm_handler]: MRM State changed: NORMAL -> MRM_OPERATING
[mrm_handler_node-27] [WARN] [1730684733.465992061] [system.mrm_handler]: MRM behavior is None. Do nothing.
[mrm_handler_node-27] [WARN] [1730684733.466432386] [system.mrm_handler]: EMERGENCY_STOP is operated.
[component_container_mt-76] [INFO] [1730684733.548544870] [control.vehicle_cmd_gate]: The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
[mrm_handler_node-27] [INFO] [1730684733.550121389] [system.mrm_handler]: MRM State changed: MRM_OPERATING -> MRM_SUCCEEDED
[component_container_mt-76] [INFO] [1730684733.637345635] [control.vehicle_cmd_gate]: The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
[mrm_handler_node-27] [INFO] [1730684733.639854425] [system.mrm_handler]: MRM State changed: MRM_SUCCEEDED -> NORMAL
[mrm_handler_node-27] [WARN] [1730684733.642659612] [system.mrm_handler]: EMERGENCY_STOP is canceled.
[autoware_ndt_scan_matcher_node-39] [INFO] [1730684733.642663457] [localization.pose_estimator.ndt_scan_matcher]: pose_buffer_.size() < 2
[mrm_handler_node-27] [INFO] [1730684733.773529695] [system.mrm_handler]: MRM State changed: NORMAL -> MRM_OPERATING
[mrm_handler_node-27] [WARN] [1730684733.773618682] [system.mrm_handler]: MRM behavior is None. Do nothing.
[mrm_handler_node-27] [WARN] [1730684733.776007653] [system.mrm_handler]: EMERGENCY_STOP is operated.
[component_container_mt-76] [INFO] [1730684733.810114161] [control.vehicle_cmd_gate]: The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
[mrm_handler_node-27] [INFO] [1730684733.811639112] [system.mrm_handler]: MRM State changed: MRM_OPERATING -> NORMAL
[mrm_handler_node-27] [WARN] [1730684733.812089326] [system.mrm_handler]: EMERGENCY_STOP is canceled.

**Comment by xmfcx** [comment]
There might be warnings but were you able to drive from A to B?

**Comment by HiHeXi** [comment]
> 可能会有警告，但您能从 A 开车到 B 吗？

Cannot drive from A to B

**Comment by xmfcx** [comment]
## Logs

Could you share the full logs to help us understand the cause?

For this,
1. Remove the logs in `~/.ros/log`
2. Run the Autoware with AWSIM Labs
3. What do you see? Do you see the localization output?
4. Share the launch log file from `~/.ros/log` here.

## Generic system information

Could you install screenfetch and share the basic system information with us?

1. `sudo apt install screenfetch -y`
2. `screenfetch -n`
3. Share the results.

### NVIDIA Driver and CUDA version

1. Run `nvidia-smi` and share the first 3 lines
> ```
> $ nvidia-smi
> Mon Nov 11 11:05:08 2024       
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
> |-----------------------------------------+----------------------+----------------------+
> ```
> 
2. Run `nvcc -V` and share the results.
> ```
> $ nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2023 NVIDIA Corporation
> Built on Wed_Nov_22_10:17:15_PST_2023
> Cuda compilation tools, release 12.3, V12.3.107
> Build cuda_12.3.r12.3/compiler.33567101_0
> ```

**Comment by HiHeXi** [comment]
```
hx@hx:~/.ros/log$ screenfetch -n
/usr/bin/screenfetch: 行 1851: -: 语法错误：需要操作数（错误记号是 "-"）
 hx@hx
 OS: Ubuntu 22.04 jammy
 Kernel: x86_64 Linux 6.8.0-48-generic
 Uptime: 7m
 Packages: 3694
 Shell: bash
 Resolution: 1920x1080
 DE: GNOME 41.7
 WM: Mutter
 WM Theme: Adwaita
 GTK Theme: Yaru [GTK2/3]
 Icon Theme: Yaru
 Font: Ubuntu 11
 Disk: 250G / 885G (30%)
 CPU: 11th Gen Intel Core i7-11800H @ 16x 4.6GHz [66.0°C]
 GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
 RAM: -
```

```
hx@hx:~/.ros/log$ nvidia-smi
Tue Nov 12 09:23:56 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5     |
|----
```


```
hx@hx:~/.ros/log$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```
[launch.log](https://github.com/user-attachments/files/17709830/launch.log)

[vehicle_velocity_converter_node_6104_1731374480717.log](https://github.com/user-attachments/files/17709832/vehicle_velocity_converter_node_6104_1731374480717.log)
[traffic_light_occlusion_predictor_node_6370_1731374480817.log](https://github.com/user-attachments/files/17709833/traffic_light_occlusion_predictor_node_6370_1731374480817.log)
[traffic_light_multi_camera_fusion_node_6395_1731374480942.log](https://github.com/user-attachments/files/17709834/traffic_light_multi_camera_fusion_node_6395_1731374480942.log)
[traffic_light_map_visualizer_node_6458_1731374481200.log](https://github.com/user-attachments/files/17709835/traffic_light_map_visualizer_node_6458_1731374481200.log)
[traffic_light_map_based_detector_node_6338_1731374480895.log](https://github.com/user-attachments/files/17709837/traffic_light_map_based_detector_node_6338_1731374480895.log)
[topic_state_monitor_node_5931_1731374480507.log](https://github.com/user-attachments/files/17709838/topic_state_monitor_node_5931_1731374480507.log)
[topic_state_monitor_node_5929_1731374480519.log](https://github.com/user-attachments/files/17709839/topic_state_monitor_node_5929_1731374480519.log)
[topic_state_monitor_node_5927_1731374480481.log](https://github.com/user-attachments/files/17709840/topic_state_monitor_node_5927_1731374480481.log)
[topic_state_monitor_node_5925_1731374480456.log](https://github.com/user-attachments/files/17709841/topic_state_monitor_node_5925_1731374480456.log)
[topic_state_monitor_node_5923_1731374480479.log](https://github.com/user-attachments/files/17709842/topic_state_monitor_node_5923_1731374480479.log)
[topic_state_monitor_node_5921_1731374480448.log](https://github.com/user-attachments/files/17709843/topic_state_monitor_node_5921_1731374480448.log)
[topic_state_monitor_node_5919_1731374480475.log](https://github.com/user-attachments/files/17709844/topic_state_monitor_node_5919_1731374480475.log)
[topic_state_monitor_node_5917_1731374480449.log](https://github.com/user-attachments/files/17709845/topic_state_monitor_node_5917_1731374480449.log)
[topic_state_monitor_node_5915_1731374480454.log](https://github.com/user-attachments/files/17709846/topic_state_monitor_node_5915_1731374480454.log)
[topic_state_monitor_node_5913_1731374480455.log](https://github.com/user-attachments/files/17709847/topic_state_monitor_node_5913_1731374480455.log)
[topic_state_monitor_node_5911_1731374480451.log](https://github.com/user-attachments/files/17709848/topic_state_monitor_node_5911_1731374480451.log)
[topic_state_monitor_node_5909_1731374480464.log](https://github.com/user-attachments/files/17709849/topic_state_monitor_node_5909_1731374480464.log)
[topic_state_monitor_node_5907_1731374480464.log](https://github.com/user-attachments/files/17709850/topic_state_monitor_node_5907_1731374480464.log)
[topic_state_monitor_node_5905_1731374480451.log](https://github.com/user-attachments/files/17709851/topic_state_monitor_node_5905_1731374480451.log)
[topic_state_monitor_node_5903_1731374480472.log](https://github.com/user-attachments/files/17709852/topic_state_monitor_node_5903_1731374480472.log)
[shape_estimation_node_6249_1731374480785.log](https://github.com/user-attachments/files/17709853/shape_estimation_node_6249_1731374480785.log)
[service_log_checker_node_5899_1731374480454.log](https://github.com/user-attachments/files/17709854/service_log_checker_node_5899_1731374480454.log)
[rviz2_6782_1731374483141.log](https://github.com/user-attachments/files/17709855/rviz2_6782_1731374483141.log)
[routing_adaptor_node_6745_1731374481446.log](https://github.com/user-attachments/files/17709856/routing_adaptor_node_6745_1731374481446.log)
[robot_state_publisher_5893_1731374480458.log](https://github.com/user-attachments/files/17709857/robot_state_publisher_5893_1731374480458.log)
[relay_6335_1731374480899.log](https://github.com/user-attachments/files/17709858/relay_6335_1731374480899.log)
[python3_6702_1731374482625.log](https://github.com/user-attachments/files/17709860/python3_6702_1731374482625.log)
[python3_5961_1731374482800.log](https://github.com/user-attachments/files/17709862/python3_5961_1731374482800.log)
[python3_5939_1731374482690.log](https://github.com/user-attachments/files/17709863/python3_5939_1731374482690.log)
[python3_4732_1731374459547.log](https://github.com/user-attachments/files/17709864/python3_4732_1731374459547.log)
[processing_time_checker_node_5897_1731374480468.log](https://github.com/user-attachments/files/17709865/processing_time_checker_node_5897_1731374480468.log)
[planning_validator_node_6572_1731374481255.log](https://github.com/user-attachments/files/17709866/planning_validator_node_6572_1731374481255.log)
[planning_evaluator_6609_1731374481063.log](https://github.com/user-attachments/files/17709867/planning_evaluator_6609_1731374481063.log)
[obstacle_pointcloud_based_validator_node_6288_1731374480736.log](https://github.com/user-attachments/files/17709868/obstacle_pointcloud_based_validator_node_6288_1731374480736.log)
[object_lanelet_filter_node_6318_1731374480837.log](https://github.com/user-attachments/files/17709869/object_lanelet_filter_node_6318_1731374480837.log)
[object_association_merger_node_6316_1731374480921.log](https://github.com/user-attachments/files/17709870/object_association_merger_node_6316_1731374480921.log)
[object_association_merger_node_6306_1731374480838.log](https://github.com/user-attachments/files/17709871/object_association_merger_node_6306_1731374480838.log)
[multi_object_tracker_node_6329_1731374480994.log](https://github.com/user-attachments/files/17709872/multi_object_tracker_node_6329_1731374480994.log)
[mrm_handler_node_5943_1731374480522.log](https://github.com/user-attachments/files/17709873/mrm_handler_node_5943_1731374480522.log)
[map_based_prediction_6333_1731374481088.log](https://github.com/user-attachments/files/17709875/map_based_prediction_6333_1731374481088.log)
[initial_pose_adaptor_node_6734_1731374481534.log](https://github.com/user-attachments/files/17709876/initial_pose_adaptor_node_6734_1731374481534.log)
[imu_corrector_node_6067_1731374480724.log](https://github.com/user-attachments/files/17709878/imu_corrector_node_6067_1731374480724.log)
[gyro_bias_estimator_node_6080_1731374480777.log](https://github.com/user-attachments/files/17709880/gyro_bias_estimator_node_6080_1731374480777.log)
[goal_pose_visualizer_6491_1731374481186.log](https://github.com/user-attachments/files/17709881/goal_pose_visualizer_6491_1731374481186.log)
[gnss_poser_6095_1731374480697.log](https://github.com/user-attachments/files/17709882/gnss_poser_6095_1731374480697.log)
[external_velocity_limit_selector_6543_1731374481177.log](https://github.com/user-attachments/files/17709883/external_velocity_limit_selector_6543_1731374481177.log)
[duplicated_node_checker_node_5895_1731374480450.log](https://github.com/user-attachments/files/17709884/duplicated_node_checker_node_5895_1731374480450.log)
[detection_by_tracker_node_6282_1731374480910.log](https://github.com/user-attachments/files/17709885/detection_by_tracker_node_6282_1731374480910.log)
[detected_object_feature_remover_node_6272_1731374480752.log](https://github.com/user-attachments/files/17709886/detected_object_feature_remover_node_6272_1731374480752.log)
[crosswalk_traffic_light_estimator_node_6433_1731374481146.log](https://github.com/user-attachments/files/17709887/crosswalk_traffic_light_estimator_node_6433_1731374481146.log)
[converter_5941_1731374480509.log](https://github.com/user-attachments/files/17709888/converter_5941_1731374480509.log)
[component_container_mt_6760_1731374481236.log](https://github.com/user-attachments/files/17709889/component_container_mt_6760_1731374481236.log)
[component_container_mt_6689_1731374481382.log](https://github.com/user-attachments/files/17709890/component_container_mt_6689_1731374481382.log)
[component_container_mt_6677_1731374481392.log](https://github.com/user-attachments/files/17709891/component_container_mt_6677_1731374481392.log)
[component_container_mt_6651_1731374480990.log](https://github.com/user-attachments/files/17709892/component_container_mt_6651_1731374480990.log)
[component_container_mt_6565_1731374481272.log](https://github.com/user-attachments/files/17709893/component_container_mt_6565_1731374481272.log)
[component_container_mt_6561_1731374481284.log](https://github.com/user-attachments/files/17709894/component_container_mt_6561_1731374481284.log)
[component_container_mt_6552_1731374481282.log](https://github.com/user-attachments/files/17709895/component_container_mt_6552_1731374481282.log)
[component_container_mt_6461_1731374480893.log](https://github.com/user-attachments/files/17709897/component_container_mt_6461_1731374480893.log)
[component_container_mt_6367_1731374480821.log](https://github.com/user-attachments/files/17709898/component_container_mt_6367_1731374480821.log)
[component_container_mt_5999_1731374480561.log](https://github.com/user-attachments/files/17709899/component_container_mt_5999_1731374480561.log)
[component_container_mt_5951_1731374480703.log](https://github.com/user-attachments/files/17709900/component_container_mt_5951_1731374480703.log)
[component_container_mt_5891_1731374480452.log](https://github.com/user-attachments/files/17709902/component_container_mt_5891_1731374480452.log)
[component_container_6549_1731374481227.log](https://github.com/user-attachments/files/17709903/component_container_6549_1731374481227.log)
[component_container_6423_1731374481175.log](https://github.com/user-attachments/files/17709904/component_container_6423_1731374481175.log)
[component_container_6058_1731374480693.log](https://github.com/user-attachments/files/17709905/component_container_6058_1731374480693.log)
[component_container_6035_1731374480716.log](https://github.com/user-attachments/files/17709906/component_container_6035_1731374480716.log)
[component_container_6001_1731374480584.log](https://github.com/user-attachments/files/17709907/component_container_6001_1731374480584.log)
[component_container_5935_1731374480513.log](https://github.com/user-attachments/files/17709908/component_container_5935_1731374480513.log)
[component_container_5933_1731374480551.log](https://github.com/user-attachments/files/17709909/component_container_5933_1731374480551.log)
[component_container_5901_1731374480450.log](https://github.com/user-attachments/files/17709910/component_container_5901_1731374480450.log)
[awsim_labs.x86_64_4474_1731374443613.log](https://github.com/user-attachments/files/17709911/awsim_labs.x86_64_4474_1731374443613.log)
[autoware_twist2accel_node_6237_1731374480717.log](https://github.com/user-attachments/files/17709912/autoware_twist2accel_node_6237_1731374480717.log)
[autoware_stop_filter_node_6223_1731374480838.log](https://github.com/user-attachments/files/17709913/autoware_stop_filter_node_6223_1731374480838.log)
[autoware_scenario_selector_node_6530_1731374481338.log](https://github.com/user-attachments/files/17709914/autoware_scenario_selector_node_6530_1731374481338.log)
[autoware_remaining_distance_time_calculator_node_6641_1731374481399.log](https://github.com/user-attachments/files/17709916/autoware_remaining_distance_time_calculator_node_6641_1731374481399.log)
[autoware_pose_instability_detector_node_6243_1731374480792.log](https://github.com/user-attachments/files/17709917/autoware_pose_instability_detector_node_6243_1731374480792.log)
[autoware_pose_initializer_node_6176_1731374480717.log](https://github.com/user-attachments/files/17709918/autoware_pose_initializer_node_6176_1731374480717.log)
[autoware_ndt_scan_matcher_node_6116_1731374480699.log](https://github.com/user-attachments/files/17709919/autoware_ndt_scan_matcher_node_6116_1731374480699.log)
[autoware_map_projection_loader_node_5989_1731374480598.log](https://github.com/user-attachments/files/17709920/autoware_map_projection_loader_node_5989_1731374480598.log)
[autoware_localization_error_monitor_node_6245_1731374480728.log](https://github.com/user-attachments/files/17709921/autoware_localization_error_monitor_node_6245_1731374480728.log)
[autoware_gyro_odometer_node_6137_1731374480585.log](https://github.com/user-attachments/files/17709922/autoware_gyro_odometer_node_6137_1731374480585.log)
[autoware_ekf_localizer_node_6208_1731374480721.log](https://github.com/user-attachments/files/17709923/autoware_ekf_localizer_node_6208_1731374480721.log)
[automatic_pose_initializer_node_6187_1731374480766.log](https://github.com/user-attachments/files/17709924/automatic_pose_initializer_node_6187_1731374480766.log)
[aggregator_node_5937_1731374480490.log](https://github.com/user-attachments/files/17709925/aggregator_node_5937_1731374480490.log)


> ## 日志
> 
> 您能否分享完整的日志以帮助我们了解原因？
> 
> 为了这，
> 
>     1. 删除登录  `~/.ros/log`
> 
>     2. 使用 AWSIM 实验室运行 Autoware
> 
>     3. 你看到了什么？您看到本地化输出了吗？
> 
>     4. 分享启动日志文件  `~/.ros/log` 这里。
> 
> 
> ## 通用系统信息
> 
> 您能安装 screenfetch 并与我们分享基本的系统信息吗？
> 
>     1. `sudo apt install screenfetch -y`
> 
>     2. `screenfetch -n`
> 
>     3. 分享结果。
> 
> 
> ### NVIDIA 驱动程序和 CUDA 版本
> 
>     1. 跑步  `nvidia-smi` 并分享前 3 行
> 
> 
> > ```
> > $ nvidia-smi
> > Mon Nov 11 11:05:08 2024       
> > +---------------------------------------------------------------------------------------+
> > | NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
> > |-----------------------------------------+----------------------+----------------------+
> > ```
> 
>     2. 跑步  `nvcc -V` 并分享结果。
> 
> 
> > ```
> > $ nvcc -V
> > nvcc: NVIDIA (R) Cuda compiler driver
> > Copyright (c) 2005-2023 NVIDIA Corporation
> > Built on Wed_Nov_22_10:17:15_PST_2023
> > Cuda compilation tools, release 12.3, V12.3.107
> > Build cuda_12.3.r12.3/compiler.33567101_0
> > ```

**Comment by xmfcx** [comment]
Autoware is compatible with CUDA 12.3.
NVIDIA Driver version compatible with CUDA 12.3 is `545.23.08`. You might want to install that. (`sudo apt install nvidia-driver-545`) (Also purge the current driver)
See the relevant table here: https://docs.nvidia.com/deploy/cuda-compatibility/#use-the-right-compat-package

Btw I don't think this problem is related to AWSIM Labs.

Could you run the following and report if they work for you?
1. https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/
  - This runs only the planning, very basic perception and system diagnostics parts.
  - This works even without a gpu. 
2. https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/
  - This runs the perception and localization on a rosbag file.
  - I don't know what is wrong with your system yet but I think this will fail for you too, but let's try it.

If they work, then we can debug further. If not, we should focus on them.

**Comment by HiHeXi** [comment]
I have uploaded the wrong video on YouTube
https://youtu.be/bXK5hAcwhLU

> Autoware 与 CUDA 12.3 兼容。 与 CUDA 12.3 兼容的 NVIDIA 驱动程序版本是 `545.23.08`。您可能想安装它。 （ `sudo apt install nvidia-driver-545`）（同时清除当前驱动程序） 请参阅此处的相关表格：https: [ //docs.nvidia.com/deploy/cuda-compatibility/#use-the-right-compat-package ](https://docs.nvidia.com/deploy/cuda-compatibility/#use-the-right-compat-package)
> 
> 顺便说一句，我不认为这个问题与 AWSIM 实验室有关。
> 
> 您可以运行以下命令并报告它们是否对您有用吗？
> 
>     1. [https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/ ](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/)
> 
> 
>     * 它仅运行规划、非常基本的感知和系统诊断部分。
> 
>     * 即使没有 GPU，这也能工作。
> 
> 
>     2. [https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/ ](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/)
> 
> 
>     * 这会在 rosbag 文件上运行感知和本地化。
> 
>     * 我还不知道你的系统出了什么问题，但我认为这对你来说也会失败，但让我们尝试一下。
> 
> 
> 如果它们有效，那么我们可以进一步调试。如果没有，我们应该关注他们。

**Comment by xmfcx** [comment]
It worked for me with the latest Autoware:

[![Video Thumbnail](https://img.youtube.com/vi/XMkRKCTN0mA/0.jpg)](https://youtu.be/XMkRKCTN0mA)

I think I've found your problem. It's here:
![image](https://github.com/user-attachments/assets/ccf3917f-27f9-4622-966d-ac11ad5a6df2)

If you follow these steps:
https://autowarefoundation.github.io/AWSIM-Labs/main/GettingStarted/QuickStartDemo/#launching-autoware

You'll see that you should use:
```
ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=awsim_labs_vehicle sensor_model:=awsim_labs_sensor_kit map_path:=<absolute path of map folder> launch_vehicle_interface:=true
```

Your vehicle_model and sensor_model are wrong.

**Comment by HiHeXi** [comment]
@xmfcx Thank you for your help. The issue has been resolved
