### ISSUE TITLE
Localization is not happening in latest version of AWSim Labs

### ISSUE THREAD

**Issue by mustaeen-7** [autowarefoundation/AWSIM-Labs#177]
I tried both AWSIM and AWSIM Labs in both localization is not happening in Rviz2 Autoware. Its flickering between initializing to Uninitialized. Can anyone please help me regarding this. I am using ubuntu 22.04 ROS2 Humble. And I cannot see any lidar scans on AWSIM interface.Below I pasted my pc screenshots
![Screenshot from 2024-11-09 19-47-41](https://github.com/user-attachments/assets/bee3ca44-9e09-4c1e-b791-93a78695a0ad)
![Screenshot from 2024-11-09 19-47-18](https://github.com/user-attachments/assets/e042b537-7f17-4345-8541-395a4e7b489a)

**Comment by maxime-clem** [comment]
Please share the Autoware log file. You can find it in `$HOME/.ros/log/{DATE-USER}/launch.log`.

**Comment by mustaeen-7** [comment]
[launch.log](https://github.com/user-attachments/files/17695608/launch.log)
Thanks for the response. Here is the log file.

**Comment by maxime-clem** [comment]
> 1731143821.3189173 [component_container_mt-59] [W] [TRT] Unable to determine GPU memory usage
1731143821.3263628 [component_container_mt-59] [W] [TRT] Unable to determine GPU memory usage
1731143821.3278058 [component_container_mt-59] [I] [TRT] [MemUsageChange] Init CUDA: CPU +4, GPU +0, now: CPU 28, GPU 0 (MiB)
1731143821.3286767 [component_container_mt-59] [W] [TRT] CUDA initialization failure with error: 100. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
1731143821.3287909 [component_container_mt-59] [E] [TRT] Fail to create builder
1731143821.8940184 [component_container_mt-1] [W] [TRT] CUDA initialization failure with error: 100

You have an issue with CUDA. Please make sure you have a Nvidia GPU and installed the drivers using the `setup-dev-env.sh` script.

**Comment by mustaeen-7** [comment]
I have installed all required drivers. Just to test I launched planning_simulator, in that I could not run the car in Auto mode after setting 2d Pose Estimate and goal point. The path is generating but all other modes are getting disabled. Here are teh screenshots below
![Screenshot from 2024-11-15 11-56-28](https://github.com/user-attachments/assets/036f467a-db6a-49db-b2f0-88bc1ffa1a8f)
![Screenshot from 2024-11-15 11-55-35](https://github.com/user-attachments/assets/60c3e28b-fd23-47cb-8735-1c7ad7531e55)
![Screenshot from 2024-11-15 11-55-14](https://github.com/user-attachments/assets/b1c1f408-4b73-4701-9f5e-389b3cfa4fb8)

**Comment by mustaeen-7** [comment]
launch.log file of above error
[launch.log](https://github.com/user-attachments/files/17770630/launch.log)

**Comment by maxime-clem** [comment]
```
1731611305.8397257 [component_container_mt-39] component_container_mt: /usr/include/eigen3/Eigen/src/Core/CwiseBinaryOp.h:116: Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::CwiseBinaryOp(const Lhs&, const Rhs&, const BinaryOp&) [with BinaryOp = Eigen::internal::scalar_sum_op<double, double>; LhsType = const Eigen::Matrix<double, -1, 1>; RhsType = const Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> > >; Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Lhs = Eigen::Matrix<double, -1, 1>; Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Rhs = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> > >]: Assertion `aLhs.rows() == aRhs.rows() && aLhs.cols() == aRhs.cols()' failed.
```
Never saw this error before. Which version of Autoware are you using ? Is this crash happening every time you start Autoware and set a goal ?

**Comment by mustaeen-7** [comment]
Yes it is happening everytime I run it. I am using latest version of Autoware. I followed this Source installation link:https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/

**Comment by mustaeen-7** [comment]
Found out the problem. It was due Nvidia Drivers for Localisation. After removing everything and reinstalling, the issue got fixed. Thanks for the support.
