### ISSUE TITLE
Add configurability of scenes, ego vehicle and initial pose of ego vehicle

### ISSUE THREAD

**Issue by WJaworskiRobotec** [autowarefoundation/AWSIM-Labs#18]
## Description
To give an option to dynamically configure simulation with a single AWSIM binary by setting the following parameters in the configuration file :
- Simulation environment
- Ego vehicle model
- Ego initial pose

This feature has been already prepared with the PR to the main AWSIM repository:
- https://github.com/tier4/AWSIM/pull/142

## Definition of done

- [x] Simulation environment (scene) can be changed using configuration file
- [x] Ego vehicle model can be changed using configuration file
- [x] Ego vehicle initial pose can be changed using configuration file

**Comment by mozhoku** [comment]
Merged changes to the main branch.
- https://github.com/autowarefoundation/AWSIM/pull/22 

Thank you for your contribution @pijaro @WJaworskiRobotec
