### ISSUE TITLE
Make multi scene setup the default

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/AWSIM-Labs#34]
With the [Add configurability of scenes, ego vehicle and initial pose of ego vehicle #18](https://github.com/autowarefoundation/AWSIM/issues/18) merged, we can now switch between scenes with a GUI.

But many functionalities from the default scene are not supported there.

Due to the new multi scene loading feature, we need to reorganize the script assignments to work with the new system.

Then, we can make it the new default.

Also, the scene creation should also be simplified and documented with all the new features added:
- Graphy
- Reset vehicle position gui
- Traffic control gui
- Main menu

**Comment by mozhoku** [comment]
Changes are merged here:
- https://github.com/autowarefoundation/AWSIM-Labs/pull/96

I'm closing this issue.
