### ISSUE TITLE
Update AWSIM to the next Unity LTS version

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/AWSIM-Labs#6]
Follow up from:
- https://github.com/tier4/AWSIM/issues/260

**Comment by Aysenayilmaz** [comment]
**Unity version :** 2022.3.21f1 

Autoware test : https://youtu.be/WzZVvt8qj1g

**Comment by mozhoku** [comment]
Changes are merged. Closing this issue. 
Thank you for the PR @Aysenayilmaz 

- https://github.com/autowarefoundation/AWSIM/pull/32
