### ISSUE TITLE
Publish V2I traffic lights signals

### ISSUE THREAD

**Issue by mozhoku** [autowarefoundation/AWSIM-Labs#73]
There should be a publisher ready for it if I'm not mistaken. Need to check to see if it works properly. If not, will fix it or make a new one.

**Comment by lchojnack** [comment]
@mozhoku 

I've implemented the V2I feature for the AWSIM. More details in the documentation [here](https://autowarefoundation.github.io/AWSIM/main/Components/Environment/V2I/)

If you want, I can take care of this task and enable the V2I feature.

**Comment by mozhoku** [comment]
@lchojnack 
Thank you, that would be great! I'll assign this task to you.

**Comment by lchojnack** [comment]
@mozhoku @xmfcx 

The V2I feature can be easily added by enabling it in the scene.

![image](https://github.com/autowarefoundation/AWSIM/assets/8416175/59f90cfd-61bc-4baf-a330-3371111a5445)

I'm wondering if we want to enable it by default or if we want a feature that allows the users to enable/disable V2I by UI. What do you think?

**Comment by mitsudome-r** [comment]
We can enable this feature as default for now, and later create toggle buttons as a separate PR.
