### ISSUE TITLE
The vehicle cannot remain stable when returned to the starting point

### ISSUE THREAD

**Issue by meliketanrikulu** [autowarefoundation/AWSIM-Labs#89]
I take the vehicle back to the starting point and wait for it to stand still. But it's starting to slip. The error does not occur every time, sometimes it works as expected. I tested with autoware 's sample vehicle.
You can find the test video showing the problem [here](https://www.youtube.com/watch?v=Xtd-zPTfDAs).

**Comment by mozhoku** [comment]
@meliketanrikulu 
That might be caused by Autoware control. I've tried it in the editor with manual gears for the vehicle.
 When gear is in:
 Parking: It does not slip.
 Drive: little sliding.
 Neutral & Reverse: it just slides back with no resistance.
 
 Video: https://youtu.be/a7cRKTTqCyY

**Comment by WJaworskiRobotec** [comment]
Proper way of resetting position is following :
- Stop Autoware
- Reset position in the simulation

Optionally, sending of stop message to Autoware could be added on the simulator side
